export const POST_LIE_REQUEST = 'POST_LIE_REQUEST'
export const POST_LIE_SUCCESS = 'POST_LIE_SUCCESS'
export const POST_LIE_FAILURE = 'POST_LIE_FAILURE'

export const GET_LIE_REQUEST = 'GET_LIE_REQUEST'
export const GET_LIE_SUCCESS = 'GET_LIE_SUCCESS'
export const GET_LIE_FAILURE = 'GET_LIE_FAILURE'
