export const POST_LIE_REQUEST = 'POST_LIE_REQUEST'
export const POST_LIE_SUCCESS = 'POST_LIE_SUCCESS'
export const POST_LIE_FAILURE = 'POST_LIE_FAILURE'

export const GET_LIE_REQUEST = 'GET_LIE_REQUEST'
export const GET_LIE_SUCCESS = 'GET_LIE_SUCCESS'
export const GET_LIE_FAILURE = 'GET_LIE_FAILURE'

export const OPEN_ENTER_LIE = 'OPEN_ENTER_LIE'
export const CLOSE_ENTER_LIE = 'CLOSE_ENTER_LIE'
export const CHANGE_ENTERED_LIE = 'CHANGE_ENTERED_LIE'

export const OPEN_PLAY_GAME = 'OPEN_PLAY_GAME'
export const CLOSE_PLAY_GAME = 'CLOSE_PLAY_GAME'
